<?php

declare(strict_types=1);

namespace tests\unit\Application\Middleware;

use Application\Command\CreateOrder;
use Domain\Order\OrderCreated;
use PHPUnit\Framework\TestCase;
use Ramsey\Uuid\Uuid;

class CollectsMessagesTest extends TestCase
{
    /** @test */
    public function it_collects_various_messages()
    {
        $this->markTestSkipped();
        $messages = [
            new CreateOrder($orderId = Uuid::uuid4(), 5),
            new OrderCreated($orderId, 5),
            'Some message',
        ];

        //  $this->messages->all()
    }

    /** @test */
    public function it_can_not_get_all_recorded_messages_twice()
    {
        $this->markTestSkipped();
        $messages = [
            new CreateOrder($orderId = Uuid::uuid4(), 5),
        ];
    }

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    protected function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }
}
